#ifndef SCREENLAYOUT_H
#define SCREENLAYOUT_H



#define PANEL_BORDER_LEFT 8
#define PANEL_BORDER_RIGHT 312  
#define PANEL_LEFT (PANEL_BORDER_LEFT + 3)
#define PANEL_RIGHT (PANEL_BORDER_RIGHT - 3)  
#define PANEL_DIVIDER_1 162

#define PANEL_CLIENT_Y1	22
#define Y_CURRENTSONG 86
#define Y_NEXTSONG (Y_CURRENTSONG+78)
#define Y_TIME 26
#define Y_SPECTRUM (Y_TIME)
#define X_SPECTRUM (PANEL_DIVIDER_1 + 13)

#define COLOR_DARK __RGB565RGB(0x40,0x40,0x40)
#define COLOR_GREY __RGB565RGB(0x70,0x70,0x70)
#define COLOR_WINDOW COLOR_GREY

#define PROGRESSBAR_X1 (PANEL_LEFT+1)
#define PROGRESSBAR_X2 (PANEL_RIGHT-1)
#define PROGRESSBAR_Y1 (Y_CURRENTSONG+103)
#define PROGRESSBAR_Y2 (Y_CURRENTSONG+111)


extern u_int16 digits[6];

#endif